# Generated by Django 3.2.3 on 2021-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
